name: Homebrew Bump Formula
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          cask: swiftplantumlapp
